from functions import sum
try:
 
 print(f'sum =  {sum(5,6)} ')
 
        
except Exception as e :
 print(e)
 